"""Golden vectors (WP-02 acceptance criterion 8, and the exit gate).

These lock the hashing scheme so an accidental change to the encoder cannot pass
review unnoticed, and so another implementation -- P4's simulator above all --
can be verified against the same fixtures before the two halves ever meet.

What this proves: the scheme has not drifted. What it does not prove: that the
scheme is correct, since the vectors were generated by the code under test. The
independent check is another implementation reproducing them.
"""

from __future__ import annotations

import json
import pathlib
from typing import Any

import pytest

from services.domain.canonical import canonical_json, digest
from services.domain.keys import approval_id, order_key, payment_key
from services.domain.vectors_data import CASES

VECTOR_FILE = (
    pathlib.Path(__file__).resolve().parents[2] / "tests" / "vectors" / "wp02" / "hashes.json"
)

DERIVERS: dict[str, Any] = {
    "approval_id": approval_id,
    "payment_key": payment_key,
    "order_key": order_key,
}


def _load() -> dict[str, Any]:
    if not VECTOR_FILE.exists():
        pytest.fail(
            f"{VECTOR_FILE} is missing. Generate it deliberately with "
            "`python scripts/generate_wp02_vectors.py`."
        )
    loaded: dict[str, Any] = json.loads(VECTOR_FILE.read_text(encoding="utf-8"))
    return loaded


VECTORS = _load()


def test_the_vector_file_declares_the_scheme_it_locks() -> None:
    assert VECTORS["scheme"] == "pp-canon-v1"


def test_there_are_vectors_to_check() -> None:
    assert len(VECTORS["vectors"]) >= 10, "a near-empty vector file would pass vacuously"


@pytest.mark.parametrize(
    "vector",
    [v for v in VECTORS["vectors"] if v["kind"] == "digest"],
    ids=lambda v: v["name"],
)
def test_digest_vectors_still_reproduce(vector: dict[str, Any]) -> None:
    payload = _payload_for(vector["name"])
    assert canonical_json(payload).decode("utf-8") == vector["canonical_json"]
    assert digest(vector["tag"], payload) == vector["digest"]


@pytest.mark.parametrize(
    "vector",
    [v for v in VECTORS["vectors"] if v["kind"] in DERIVERS],
    ids=lambda v: v["name"],
)
def test_derived_key_vectors_still_reproduce(vector: dict[str, Any]) -> None:
    derive = DERIVERS[vector["kind"]]
    assert derive(**vector["inputs"]) == vector["digest"]


def _payload_for(name: str) -> object:
    for case in CASES["digests"]:
        if case["name"] == name:
            return case["payload"]
    raise AssertionError(f"no case named {name!r}; vectors and cases have drifted apart")


def test_every_case_has_a_vector_and_every_vector_has_a_case() -> None:
    """Catches a case added without regenerating, and a stale vector left behind."""
    case_names = {case["name"] for case in CASES["digests"]}
    vector_names = {v["name"] for v in VECTORS["vectors"] if v["kind"] == "digest"}
    assert case_names == vector_names, (
        "regenerate with `python scripts/generate_wp02_vectors.py` after changing cases"
    )


def test_the_live_and_fixture_quote_vectors_differ() -> None:
    """The mode binding, pinned as a vector so it cannot be quietly dropped."""
    by_name = {v["name"]: v for v in VECTORS["vectors"]}
    live = by_name["quote: single line, one known delivery charge"]
    fixture = by_name["quote: identical to the first but in fixture mode"]
    assert live["digest"] != fixture["digest"]


def test_every_digest_is_lowercase_hex_sha256() -> None:
    for vector in VECTORS["vectors"]:
        value = vector["digest"]
        assert len(value) == 64 and value == value.lower()
        int(value, 16)
