"""Regenerate the WP-02 golden vectors.

Run deliberately, never from a test:

    python scripts/generate_wp02_vectors.py

The vectors are a contract with every other package that computes a ProofPath
hash -- P4's simulator most of all. Regenerating them is a breaking change to
that contract and needs the two approvals the POA mandates for payment-state
changes, so the diff should be reviewed, not waved through.

Honest framing: because these are generated by the same code the tests check,
they are a *regression* guard against an accidental change to the scheme, not an
independent proof that the scheme is right. Their value is cross-package: another
implementation must reproduce them byte for byte.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from services.domain.canonical import (  # noqa: E402
    TAG_DIFF,
    TAG_IDEMPOTENCY,
    TAG_LINES,
    TAG_QUOTE,
    canonical_json,
    digest,
)
from services.domain.keys import (  # noqa: E402
    approval_id,
    order_key,
    payment_key,
)
from services.domain.vectors_data import CASES  # noqa: E402

OUTPUT = pathlib.Path(__file__).resolve().parents[1] / "tests" / "vectors" / "wp02" / "hashes.json"

_TAGS = {
    "quote": TAG_QUOTE,
    "diff": TAG_DIFF,
    "lines": TAG_LINES,
    "idempotency": TAG_IDEMPOTENCY,
}


def build() -> dict[str, object]:
    vectors: list[dict[str, object]] = []

    for case in CASES["digests"]:
        tag = _TAGS[case["tag"]]
        payload = case["payload"]
        vectors.append(
            {
                "name": case["name"],
                "kind": "digest",
                "tag": tag,
                "canonical_json": canonical_json(payload).decode("utf-8"),
                "digest": digest(tag, payload),
            }
        )

    for case in CASES["approval_ids"]:
        vectors.append(
            {"name": case["name"], "kind": "approval_id", "inputs": case["inputs"],
             "digest": approval_id(**case["inputs"])}
        )

    for case in CASES["payment_keys"]:
        vectors.append(
            {"name": case["name"], "kind": "payment_key", "inputs": case["inputs"],
             "digest": payment_key(**case["inputs"])}
        )

    for case in CASES["order_keys"]:
        vectors.append(
            {"name": case["name"], "kind": "order_key", "inputs": case["inputs"],
             "digest": order_key(**case["inputs"])}
        )

    return {
        "scheme": "pp-canon-v1",
        "note": "Regenerating this file is a breaking contract change. See WP-02.",
        "vectors": vectors,
    }


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(build(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {len(build()['vectors'])} vectors to {OUTPUT}")  # noqa: T201


if __name__ == "__main__":
    main()
